# Generated by Django 4.0.3 on 2022-04-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No currency', max_length=100, null=True)),
                ('icon', models.URLField(default='www.google.com', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_rank', models.CharField(default=0, max_length=10)),
                ('currency_name', models.CharField(default='0', max_length=100)),
                ('symbol', models.CharField(default='N/A', max_length=10)),
                ('currency_price', models.CharField(default='0', max_length=100)),
                ('percent_change_24h', models.CharField(default='0', max_length=100)),
                ('percent_change_7d', models.CharField(default='0', max_length=100)),
                ('percent_change_1h', models.CharField(default='0', max_length=100)),
                ('market_cap', models.CharField(default='0', max_length=100)),
                ('percent_change_30d', models.CharField(default='0', max_length=100)),
                ('percent_change_60d', models.CharField(default='0', max_length=100)),
                ('percent_change_90d', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
