# Generated by Django 4.0.3 on 2022-03-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100)),
                ('symbol', models.URLField()),
                ('currency_price', models.CharField(max_length=100)),
                ('currency_rank', models.CharField(max_length=20)),
                ('market_value', models.CharField(max_length=100)),
            ],
        ),
    ]
