# Generated by Django 4.0.3 on 2022-04-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='market_value',
        ),
        migrations.AddField(
            model_name='status',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='market_cap',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='status',
            name='percent_change_1h',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='status',
            name='percent_change_24h',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='status',
            name='percent_change_7d',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='currency_name',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='currency_price',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='currency_rank',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='symbol',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
