# Generated by Django 4.0.3 on 2022-04-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_remove_status_market_value_status_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='image',
        ),
        migrations.AlterField(
            model_name='status',
            name='currency_rank',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
