# Generated by Django 4.0.3 on 2022-04-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_remove_status_image_alter_status_currency_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crypto',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
